[versions]
compileSdk = "32"
targetSdk = "32"
minSdk = "21"
androidGradle = "7.2.1"
ktlint = "0.45.2"
jvm = "1.8"
prettier = "2.6.0"
prettierPluginXml = "1.2.0"
material = "1.5.0"
junit = "4.13.2"
androidxJunit = "1.1.3"
androidxEspressoCore = "3.4.0"
kotlin = "1.6.20"
spotless = "6.4.2"
detekt = "1.19.0"

[plugins]
androidGradle = { id = "com.android.application", version.ref = "androidGradle" }
androidKotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidxEspressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspressoCore" }
